### ISSUE TITLE
Authentification graphite-web failed

### ISSUE THREAD

**Issue by lilian-benoit** [deividgdt/resynthesize#3]
Hi !

On CentOS 8.3, I have installed graphite-web via your script but i failed to login on graphite-web.

admin / graphite_me_synthesize don't work.

Any ideas ?

PS : It's OK for grafana.

**Comment by deividgdt** [comment]
Hi Lilian,

I'll take a look into this, I don't know, maybe now it's too late, but you can change the default password with the following commands:
`
$ cd /opt/graphite/webapp/graphite
`
`
$ sudo python manage.py changepassword admin
`

Kind regards,

**Comment by lilian-benoit** [comment]
Hi David.

I show this command on your README but script `manage.py` don't exist on folder `/opt/graphite/webapp/graphite`

Regards

**Comment by lilian-benoit** [comment]
I found a solution
'PYTHONPATH=/opt/graphite/webapp django-admin.py createsuperuser --settings=graphite.settings'

I can prepare an other PR for this.

Regards.

**Comment by deividgdt** [comment]
Hi Lilian,

Thanks for your help!

**Comment by deividgdt** [comment]
Solved.
